# Copyright (c) 2017 Shotgun Software Inc.
description: Apps and Engines when launching with a project only context.

includes:
- ./includes/frameworks.yml
- ./includes/settings/tk-desktop.yml
- ./includes/settings/tk-maya.yml
- ./includes/settings/tk-nuke.yml
- ./includes/settings/tk-photoshopcc.yml
- ./includes/settings/tk-aftereffects.yml
- ./includes/settings/tk-shell.yml
- ./includes/settings/tk-shotgun.yml

engines:
  tk-desktop:      "@settings.tk-desktop.project"
  tk-maya:         "@settings.tk-maya.project"
  tk-nuke:         "@settings.tk-nuke.project"
  tk-photoshopcc:  "@settings.tk-photoshopcc.project"
  tk-aftereffects: "@settings.tk-aftereffects.project"
  tk-shell:        "@settings.tk-shell.project"
  tk-shotgun:      "@settings.tk-shotgun.project"

frameworks: "@frameworks"
